services:
  nvidia-stock-bot:
    image: nvidia-stock-bot
    container_name: nvidia-stock-bot
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - DISCORD_WEBHOOK_URL=${DS_HOOK}
      - REFRESH_TIME=${FREQ}
      - API_URL_SKU=${API_URL_SKU}
      - API_URL_STOCK=${API_URL_STOCK}
      - PRODUCT_URL=${PRODUCT_URL}
      - PRODUCT_NAME=${PRODUCT_NAME}
      - PYTHONUNBUFFERED=1 # Allow to display log in real-time
    command: python nvidia-stock-bot.py # Run the script