services:
  nvidia-stock-bot:
    image: nvidia-stock-bot
    container_name: nvidia-stock-bot
    restart: unless-stopped
    env_file:
      - .env
    environment:
    # Minimal environment variables
      environment:
    # Minimal environment variables
      - PRODUCT_NAMES=${PRODUCT_NAMES}
      - DISCORD_WEBHOOK_URL=${DISCORD_WEBHOOK_URL}
      - COUNTRY=${COUNTRY}                        
      - PYTHONUNBUFFERED=1