services:
  nvidia-stock-bot:
    image: nvidia-stock-bot
    container_name: nvidia-stock-bot
    restart: unless-stopped
    env_file:
      - .env
    environment:
    # Minimal environment variables
      - PRODUCT_NAMES=                  # Exact GPU name (e.g. "RTX 5080, RTX 5090")
      - DISCORD_WEBHOOK_URL=            # Your Discord webhook URL
      - DISCORD_NOTIFICATION_CURRENCY=  # Set your country currency
      - API_URL_SKU=                    # API listing the product for your country
      - API_URL_STOCK=                  # API providing stock data for your country
      - PRODUCT_URL=                    # GPU purchase URL for your country
      - PYTHONUNBUFFERED=1              # Enables real-time log output